### ISSUE TITLE
Settings not accesible (server error)

### ISSUE THREAD

**Issue by lexislav** [barrelstrength/sprout-redirects#40]
### Description

Plugin works just fine, but the plugin settings are not accesible - Internal error screen. From weblog it seems the CP's tamplete could not be found. Weblog attached.

Plugin installed in Lite version.

PHP version | 8.1.11
-- | --
Linux 4.18.0-372.9.1.1.lve.el8.x86_64
MySQL 10.5.16
Imagick 3.7.0 (ImageMagick 7.1.0-20)
Craft Pro 4.3.10
2.0.47
v3.4.3
7.5.0

Sprout Redirects | 4.44.445
-- | --

[web-2023-03-02.log](https://github.com/barrelstrength/craft-sprout-redirects/files/10876323/web-2023-03-02.log)

### How to reproduce

The error only occur on live server (https://www.hostinger.co.uk). Setting page in CP works just fine.
So hard not sure how to reproduce.

### Sprout Version

Sprout Redirects | 4.44.445

### Craft Version

4.3.10

### Database Type Version

MySQL 10.5.16

**Comment by BenParizek** [comment]
@lexislav I'm unable to reproduce this. Do you by chance have the [allowAdminChanges config](https://craftcms.com/docs/3.x/config/config-settings.html#allowadminchanges) setting set to `false` for the live environment?

Looking at this more closely, it does appear Sprout pulls in the redirects settings file with an include that uses casing that doesn't match the file casing, so perhaps your server has different treatment of casing in filenames which is causing this issue. I'm not sure if this would explain your other issue too (https://github.com/barrelstrength/sprout-redirects/issues/41) but have pushed an update to clean up any mismatched casing references.

For the moment, you can run `composer update` to get the latest Sprout dependency or I'll tag a new Sprout Redirects release shortly and update and close this ticket once I do.

**Comment by lexislav** [comment]
Thanks @BenParizek, the update have fixed this issue - I can access the redirects settings now.
