### ISSUE TITLE
404 page not loading with activated plugin

### ISSUE THREAD

**Issue by lexislav** [barrelstrength/sprout-redirects#41]
### Description

The rediretcs works as should, but 404 page is not loaded with activated plugin. Getting Internal error message instead.
When plugin is deactivated, 404 page/template is loading as it should.
I have tried to locate some 404 page settings in plugin's docs but without success.
Any tip how to fix this would help.

### How to reproduce

Enter wrong URL :-)

### Sprout Version

4.44.445

### Craft Version

Craft Pro 4.3.10

### Database Type Version

MySQL 5.7.41

**Comment by BenParizek** [comment]
@lexislav I'm unable to recreate this. Sprout Redirects doesn't do anything in addition to Craft for displaying 404s. It logs them, checks if any redirects exist, and if no redirects exist, just lets Craft handle the 404.

Is it possible you are using a custom `404.twig` template and doing something in that template that's causing the internal server error? If so, perhaps deleting that custom template for a moment and letting Craft handle the 404 on it's own would help answer if that's the case.

If this issue continues, to further troubleshoot, I'll need more specific steps of how to recreate what you are seeing.

**Comment by BenParizek** [comment]
Please re-open with additional details if this issue returns.
